{{- if and .Values.forgejo.enabled .Values.forgejo.gitea.demo }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: forgejo-admin-secret
  labels:
{{ include "kubezero-lib.labels" . | indent 4 }}
data:
  username: {{ "demo" | b64enc | quote }}
  password: {{ "secret" | b64enc | quote }}
{{- end }}
