apiVersion: v2
name: kubezero-aws-efs-csi-driver
description: KubeZero Umbrella Chart for aws-efs-csi-driver
version: 0.1.1
appVersion: 1.0.0
kubeVersion: ">=1.16.0-0"
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/kubezero/logo-small-64.png
sources:
  - https://github.com/Zero-Down-Time/kubezero
  - https://github.com/kubernetes-sigs/aws-efs-csi-driver
keywords:
  - kubezero
  - aws
  - efs
  - csi
maintainers:
  - name: Quarky9
dependencies:
  - name: kubezero-lib
    version: ">= 0.1.3"
    repository: https://zero-down-time.github.io/kubezero/
# Once they properly update upstream
#  - name: aws-ebs-csi-driver
#    version: 1.0.0
#    repository: https://kubernetes-sigs.github.io/aws-efs-csi-driver
