apiVersion: v2
description: KubeZero ArgoCD Helm chart to install ArgoCD itself and the KubeZero ArgoCD Application
name: kubezero-argo-cd
version: 0.3.9
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/kubezero/logo-small-64.png
keywords:
  - kubezero
  - argocd
  - gitops
maintainers:
  - name: Quarky9
dependencies:
dependencies:
  - name: kubezero-lib
    version: ">= 0.1.3"
    repository: https://zero-down-time.github.io/kubezero/
  - name: argo-cd
    version: 2.6.0
    repository: https://argoproj.github.io/argo-helm
kubeVersion: ">= 1.16.0"
