apiVersion: v2
name: kubezero-keyvalue
description: KubeZero KeyValue Module
type: application
version: 0.1.0
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/kubezero/logo-small-64.png
keywords:
  - kubezero
  - redis
  - redis-cluster
maintainers:
  - name: Stefan Reimer
    email: stefan@zero-downtime.net
dependencies:
  - name: kubezero-lib
    version: ">= 0.1.6"
    repository: https://cdn.zero-downtime.net/charts/
  - name: redis
    version: 20.0.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: redis-cluster
    version: 11.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis-cluster.enabled

kubeVersion: ">= 1.26.0"
