{{- if .Values.garage.enabled }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ printf "%s-rpc-secret" .Release.Name | trunc 63 | trimSuffix "-" }}
type: Opaque
stringData:
  rpcSecret: "{{ .Values.garage.garage.rpcSecret }}"
{{- end }}
