apiVersion: v2
name: kubezero-local-volume-provisioner
description: KubeZero Umbrella Chart for local-static-provisioner
type: application
version: 0.0.1
appVersion: 2.3.4
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/kubezero/logo-small-64.png
keywords:
  - kubezero
  - local-static-provisioner
maintainers:
  - name: Quarky9
dependencies:
  - name: kubezero-lib
    version: ">= 0.1.1"
    repository: https://zero-down-time.github.io/kubezero/
kubeVersion: ">= 1.16.0"
