apiVersion: v2
name: kubezero-analytics
description: KubeZero Analytics module
type: application
version: 0.1.2
home: https://kubezero.com
icon: https://cdn.zero-downtime.net/assets/kubezero/logo-small-64.png
keywords:
  - kubezero
  - unami
maintainers:
  - name: Stefan Reimer
    email: stefan@zero-downtime.net
dependencies:
  - name: umami
    version: 7.7.0
    repository: https://charts.christianhuth.de
    condition: umami.enabled
  - name: kubezero-lib
    version: 0.2.1
    repository: https://cdn.zero-downtime.net/charts/
kubeVersion: ">= 1.30.0-0"
